/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndpointsCategoryRouteImport } from './routes/endpoints.$category'
import { Route as ApiToolsSswebRouteImport } from './routes/api.tools.ssweb'
import { Route as ApiToolsShortenRouteImport } from './routes/api.tools.shorten'
import { Route as ApiToolsQrRouteImport } from './routes/api.tools.qr'
import { Route as ApiAiImagineRouteImport } from './routes/api.ai.imagine'
import { Route as ApiAiGpt4oRouteImport } from './routes/api.ai.gpt4o'
import { Route as ApiAiGeminiRouteImport } from './routes/api.ai.gemini'
import { Route as ApiAiClaudeRouteImport } from './routes/api.ai.claude'
import { Route as ApiAiAiRouteImport } from './routes/api.ai.ai'

const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsCategoryRoute = EndpointsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => EndpointsRoute,
} as any)
const ApiToolsSswebRoute = ApiToolsSswebRouteImport.update({
  id: '/api/tools/ssweb',
  path: '/api/tools/ssweb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsShortenRoute = ApiToolsShortenRouteImport.update({
  id: '/api/tools/shorten',
  path: '/api/tools/shorten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsQrRoute = ApiToolsQrRouteImport.update({
  id: '/api/tools/qr',
  path: '/api/tools/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImagineRoute = ApiAiImagineRouteImport.update({
  id: '/api/ai/imagine',
  path: '/api/ai/imagine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGpt4oRoute = ApiAiGpt4oRouteImport.update({
  id: '/api/ai/gpt4o',
  path: '/api/ai/gpt4o',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGeminiRoute = ApiAiGeminiRouteImport.update({
  id: '/api/ai/gemini',
  path: '/api/ai/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiClaudeRoute = ApiAiClaudeRouteImport.update({
  id: '/api/ai/claude',
  path: '/api/ai/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAiRoute = ApiAiAiRouteImport.update({
  id: '/api/ai/ai',
  path: '/api/ai/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
  '/api/ai/ai': typeof ApiAiAiRoute
  '/api/ai/claude': typeof ApiAiClaudeRoute
  '/api/ai/gemini': typeof ApiAiGeminiRoute
  '/api/ai/gpt4o': typeof ApiAiGpt4oRoute
  '/api/ai/imagine': typeof ApiAiImagineRoute
  '/api/tools/qr': typeof ApiToolsQrRoute
  '/api/tools/shorten': typeof ApiToolsShortenRoute
  '/api/tools/ssweb': typeof ApiToolsSswebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
  '/api/ai/ai': typeof ApiAiAiRoute
  '/api/ai/claude': typeof ApiAiClaudeRoute
  '/api/ai/gemini': typeof ApiAiGeminiRoute
  '/api/ai/gpt4o': typeof ApiAiGpt4oRoute
  '/api/ai/imagine': typeof ApiAiImagineRoute
  '/api/tools/qr': typeof ApiToolsQrRoute
  '/api/tools/shorten': typeof ApiToolsShortenRoute
  '/api/tools/ssweb': typeof ApiToolsSswebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
  '/api/ai/ai': typeof ApiAiAiRoute
  '/api/ai/claude': typeof ApiAiClaudeRoute
  '/api/ai/gemini': typeof ApiAiGeminiRoute
  '/api/ai/gpt4o': typeof ApiAiGpt4oRoute
  '/api/ai/imagine': typeof ApiAiImagineRoute
  '/api/tools/qr': typeof ApiToolsQrRoute
  '/api/tools/shorten': typeof ApiToolsShortenRoute
  '/api/tools/ssweb': typeof ApiToolsSswebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
    | '/api/ai/ai'
    | '/api/ai/claude'
    | '/api/ai/gemini'
    | '/api/ai/gpt4o'
    | '/api/ai/imagine'
    | '/api/tools/qr'
    | '/api/tools/shorten'
    | '/api/tools/ssweb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
    | '/api/ai/ai'
    | '/api/ai/claude'
    | '/api/ai/gemini'
    | '/api/ai/gpt4o'
    | '/api/ai/imagine'
    | '/api/tools/qr'
    | '/api/tools/shorten'
    | '/api/tools/ssweb'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
    | '/api/ai/ai'
    | '/api/ai/claude'
    | '/api/ai/gemini'
    | '/api/ai/gpt4o'
    | '/api/ai/imagine'
    | '/api/tools/qr'
    | '/api/tools/shorten'
    | '/api/tools/ssweb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  EndpointsRoute: typeof EndpointsRouteWithChildren
  ApiAiAiRoute: typeof ApiAiAiRoute
  ApiAiClaudeRoute: typeof ApiAiClaudeRoute
  ApiAiGeminiRoute: typeof ApiAiGeminiRoute
  ApiAiGpt4oRoute: typeof ApiAiGpt4oRoute
  ApiAiImagineRoute: typeof ApiAiImagineRoute
  ApiToolsQrRoute: typeof ApiToolsQrRoute
  ApiToolsShortenRoute: typeof ApiToolsShortenRoute
  ApiToolsSswebRoute: typeof ApiToolsSswebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$category': {
      id: '/endpoints/$category'
      path: '/$category'
      fullPath: '/endpoints/$category'
      preLoaderRoute: typeof EndpointsCategoryRouteImport
      parentRoute: typeof EndpointsRoute
    }
    '/api/tools/ssweb': {
      id: '/api/tools/ssweb'
      path: '/api/tools/ssweb'
      fullPath: '/api/tools/ssweb'
      preLoaderRoute: typeof ApiToolsSswebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/shorten': {
      id: '/api/tools/shorten'
      path: '/api/tools/shorten'
      fullPath: '/api/tools/shorten'
      preLoaderRoute: typeof ApiToolsShortenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/qr': {
      id: '/api/tools/qr'
      path: '/api/tools/qr'
      fullPath: '/api/tools/qr'
      preLoaderRoute: typeof ApiToolsQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/imagine': {
      id: '/api/ai/imagine'
      path: '/api/ai/imagine'
      fullPath: '/api/ai/imagine'
      preLoaderRoute: typeof ApiAiImagineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/gpt4o': {
      id: '/api/ai/gpt4o'
      path: '/api/ai/gpt4o'
      fullPath: '/api/ai/gpt4o'
      preLoaderRoute: typeof ApiAiGpt4oRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/gemini': {
      id: '/api/ai/gemini'
      path: '/api/ai/gemini'
      fullPath: '/api/ai/gemini'
      preLoaderRoute: typeof ApiAiGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/claude': {
      id: '/api/ai/claude'
      path: '/api/ai/claude'
      fullPath: '/api/ai/claude'
      preLoaderRoute: typeof ApiAiClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/ai': {
      id: '/api/ai/ai'
      path: '/api/ai/ai'
      fullPath: '/api/ai/ai'
      preLoaderRoute: typeof ApiAiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EndpointsRouteChildren {
  EndpointsCategoryRoute: typeof EndpointsCategoryRoute
}

const EndpointsRouteChildren: EndpointsRouteChildren = {
  EndpointsCategoryRoute: EndpointsCategoryRoute,
}

const EndpointsRouteWithChildren = EndpointsRoute._addFileChildren(
  EndpointsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  EndpointsRoute: EndpointsRouteWithChildren,
  ApiAiAiRoute: ApiAiAiRoute,
  ApiAiClaudeRoute: ApiAiClaudeRoute,
  ApiAiGeminiRoute: ApiAiGeminiRoute,
  ApiAiGpt4oRoute: ApiAiGpt4oRoute,
  ApiAiImagineRoute: ApiAiImagineRoute,
  ApiToolsQrRoute: ApiToolsQrRoute,
  ApiToolsShortenRoute: ApiToolsShortenRoute,
  ApiToolsSswebRoute: ApiToolsSswebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
