/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndpointsCategoryRouteImport } from './routes/endpoints.$category'

const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsCategoryRoute = EndpointsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => EndpointsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/endpoints': typeof EndpointsRouteWithChildren
  '/endpoints/$category': typeof EndpointsCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/endpoints'
    | '/endpoints/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  EndpointsRoute: typeof EndpointsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$category': {
      id: '/endpoints/$category'
      path: '/$category'
      fullPath: '/endpoints/$category'
      preLoaderRoute: typeof EndpointsCategoryRouteImport
      parentRoute: typeof EndpointsRoute
    }
  }
}

interface EndpointsRouteChildren {
  EndpointsCategoryRoute: typeof EndpointsCategoryRoute
}

const EndpointsRouteChildren: EndpointsRouteChildren = {
  EndpointsCategoryRoute: EndpointsCategoryRoute,
}

const EndpointsRouteWithChildren = EndpointsRoute._addFileChildren(
  EndpointsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  EndpointsRoute: EndpointsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
